Commenting out test storing attempts again

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -88,11 +88,11 @@ jobs:
         id: playwright-tests
         run: |
           # This one is functioning, but I want to set conditionals
-          #docker run --rm playwright-tests > playwright-results.txt || true
+          docker run --rm playwright-tests > playwright-results.txt || true
           
-          docker run --rm playwright-tests > playwright-results.txt
-          echo "result=$(grep -c 'fail' playwright-results.txt)" >> $GITHUB_ENV
-          echo "Playwright tests result: ${{ env.result }}"
+          #docker run --rm playwright-tests > playwright-results.txt
+          #echo "result=$(grep -c 'fail' playwright-results.txt)" >> $GITHUB_ENV
+          #echo "Playwright tests result: ${{ env.result }}"
 
 
       # TODO: figure out how to save from Docker    
@@ -132,7 +132,8 @@ jobs:
   deploy:
     runs-on: ubuntu-latest
     needs: build-and-test
-    if: success() && needs.build-and-test.outputs.playwright-tests == '0'
+    #if: success() && needs.build-and-test.outputs.playwright-tests == '0'
+    
     #if: success() # TODO still figuring out playwright implementation
     #if: success() && needs.build-and-test.outputs.playwright-tests == 'true'
 
