Update main.yml to deploy only after playwright tests also successful

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -84,7 +84,16 @@ jobs:
       
       - name: Run Playwright tests in Docker
         run: |
-          docker run --rm playwright-tests > playwright-results.txt || true
+          # This one is funcitoning, but I want to set conditionals
+          #docker run --rm playwright-tests > playwright-results.txt || true
+
+          if docker run --rm playwright-tests > playwright-results.txt; then
+            echo "playwright-tests=true" >> $GITHUB_ENV
+            echo "SUCCESS: Check report in playwright-results.txt"
+          else
+            echo "playwright-tests=false" >> $GITHUB_ENV
+            echo "FAILURE: Check report in playwright-results.txt"
+          fi
     
    
       #- name: Install Playwright dependencies
@@ -122,7 +131,7 @@ jobs:
     runs-on: ubuntu-latest
     needs: build-and-test
     #if: github.event_name == 'push'
-    if: success() 
+    if: success() && env.playwright-tests == 'true'
 
     steps:
       - name: Checkout Hexo repository
@@ -146,9 +155,6 @@ jobs:
         run: |
             npx hexo clean
             npx hexo generate
-        
-      #- name: List contents of publish directory
-      #  run: ls -la ./blog/public 
         
       - name: Deploy to GitHub Pages
         uses: peaceiris/actions-gh-pages@v3
