add more debug messages for running tests

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -117,13 +117,13 @@ jobs:
         id: playwright-tests
         run: |
           # This one is functioning, but I want to set conditionals
-          docker run --rm playwright-tests > playwright-results.txt || true
+          docker run --rm playwright-tests > playwright-results.txt ||  echo "Docker command failed"
 
-          result=$(grep -c 'fail' playwright-results.txt)
+          result=$(grep -c 'fail' playwright-results.txt || echo "All tests passed")
           echo "result=$result" >> $GITHUB_OUTPUT
           echo "Playwright tests result: $result"
 
-          #docker run --rm playwright-tests > playwright-results.txt
+
           #echo "result=$(grep -c 'fail' playwright-results.txt)" >> $GITHUB_ENV
           #echo "Playwright tests result: ${{ env.result }}"
 
