Attempting to save test results again

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -85,14 +85,15 @@ jobs:
           docker build -t playwright-tests .
       
       - name: Run Playwright tests in Docker
+        id: playwright-tests
         run: |
           # This one is functioning, but I want to set conditionals
-          docker run --rm playwright-tests > playwright-results.txt || true
+          #docker run --rm playwright-tests > playwright-results.txt || true
           
-          #container_id=$(docker run -d -v ${{ github.workspace }}/is373-project/results:/results playwright-tests)
-          #docker wait $container_id
-          #docker cp $container_id:/results/playwright-results.txt ${{ github.workspace }}/is373-project/test-results/playwright-results.txt
-          #docker rm $container_id
+          docker run --rm playwright-tests > playwright-results.txt
+          echo "result=$(grep -c 'fail' playwright-results.txt)" >> $GITHUB_ENV
+          echo "Playwright tests result: ${{ env.result }}"
+
 
       # TODO: figure out how to save from Docker    
       #- name: Save Test Results
@@ -131,6 +132,7 @@ jobs:
   deploy:
     runs-on: ubuntu-latest
     needs: build-and-test
+    if: success() && needs.build-and-test.outputs.playwright-tests == '0'
     #if: success() # TODO still figuring out playwright implementation
     #if: success() && needs.build-and-test.outputs.playwright-tests == 'true'
 
